function generatePassNumber() {
    // Get the current date
    const currentDate = new Date();
    const day = String(currentDate.getDate()).padStart(2, '0');
    const month = String(currentDate.getMonth() + 1).padStart(2, '0');
    const year = currentDate.getFullYear();
  
    // Generate the sequential number
    let sequentialNumber = localStorage.getItem('sequentialNumber') || '000001';
    const nextSequentialNumber = String(parseInt(sequentialNumber) + 1).padStart(4, '0');
    localStorage.setItem('sequentialNumber', nextSequentialNumber);
  
    // Construct the pass number
    const passNumber = `${day}/${month}/${year}/${sequentialNumber}`;
  
    // Display the pass number in the form
    document.getElementById('passnumber').value = passNumber;
  }

  function getCurrentTime() {
    var currentTime = new Date().toLocaleTimeString();
    document.getElementById("visitorentrytime").value = currentTime;
    document.getElementById("gatepassgenerationtime").value = currentTime;
  }
  function printForm() {
    var passnumber = document.getElementById("passnumber").value;
    var visitorsname = document.getElementById("visitorsname").value;
    var visitorsgender = document.getElementById("visitorsgender").value;
    var visitorsidtype = document.getElementById("visitorsidtype").value;
    var iddetails = document.getElementById("iddetails").value;
    var purposeofvisit = document.getElementById("purposeofvisit").value;
    var visitingdepartment = document.getElementById("visitingdepartment").value;
    var mobilenumber = document.getElementById("mobilenumber").value;
    var visitorentrytime = document.getElementById("visitorentrytime").value;
    var gatepassgenerationtime = document.getElementById("gatepassgenerationtime").value;
    var passcreatedby = document.getElementById("passcreatedby").value;
    var visitorsphoto = document.getElementById("visitorsphoto").value;
    
    var printContent = "<h2>Visitor's Details</h2>";
    printContent += "<p>Gate Pass Number: " + passnumber + "</p>";
    printContent += "<p>Visitor's Name: " + visitorsname + "</p>";
    printContent += "<p>Visitor's Gender: " + visitorsgender + "</p>";
    printContent += "<p>Visitor's ID Type: " + visitorsidtype + "</p>";
    printContent += "<p>ID Details: " + iddetails + "</p>";
    printContent += "<p>Purpose of Visit: " + purposeofvisit + "</p>";
    printContent += "<p>Visiting Department: " + visitingdepartment + "</p>";
    printContent += "<p>Mobile Number:" + mobilenumber + "</p>";
    printContent += "<p>Visitor Entry Time: " + visitorentrytime + "</p>";
    printContent += "<p>Gate Pass Generation Time: " + gatepassgenerationtime + "</p>";
    printContent += "<p>Pass Generated By: " + passcreatedby + "</p>";
    printContent += "<p>Visitor's Photo: " + visitorsphoto + "</p>";
  
    var printDiv = document.createElement("div");
printDiv.innerHTML = printContent;
document.body.appendChild(printDiv);

window.print();
document.body.removeChild(printDiv);
  }